#  git submodule add https://github.com/tpope/vim-pathogen.git
  git submodule add https://github.com/alfredodeza/pytest.vim.git bundle/py.test
  git submodule add https://github.com/dradtke/OmniCppComplete.git bundle/OmniCppComplete
  git submodule add https://github.com/ervandew/supertab.git bundle/supertab
  git submodule add https://github.com/fholgado/minibufexpl.vim.git bundle/minibufexpl
  git submodule add https://github.com/fs111/pydoc.vim.git bundle/pydoc
  git submodule add https://github.com/FromtonRouge/OmniCppComplete.git bundle/OmniCppComplete
  git submodule add https://github.com/jacquesbh/vim-showmarks.git bundle/showmarks
  git submodule add https://github.com/mileszs/ack.vim.git bundle/ack
  git submodule add https://github.com/msanders/snipmate.vim.git bundle/snipmate
  git submodule add https://github.com/majutsushi/tagbar.git bundle/tagbar
  git submodule add https://github.com/mitechie/pyflakes-pathogen.git bundle/pyflakes-pathogen
  git submodule add https://github.com/python-rope/ropevim.git bundle/ropevim
  git submodule add https://github.com/reinh/vim-makegreen bundle/makegreen
  git submodule add https://github.com/rkulla/pydiction.git bundle/pydiction
  git submodule add https://github.com/scrooloose/syntastic.git bundle/syntastic
  git submodule add https://github.com/sjl/gundo.vim.git bundle/gundo
  git submodule add https://github.com/tpope/vim-fugitive.git bundle/fugitive
  git submodule add https://github.com/tpope/vim-surround.git bundle/surround
  git submodule add https://github.com/tpope/vim-git.git bundle/git
  git submodule add https://github.com/tpope/vim-git.git bundle/git
  git submodule add https://github.com/vim-scripts/LaTeX-Suite-aka-Vim-LaTeX.git bundle/latex-suite
  git submodule add https://github.com/vim-scripts/ctags.vim.git bundle/ctags
  git submodule add https://github.com/vim-scripts/TaskList.vim.git bundle/tasklist
  git submodule add https://github.com/vim-scripts/The-NERD-tree.git bundle/nerdtree
  git submodule add https://github.com/vim-scripts/pep8.git bundle/pep8
  git submodule add https://github.com/vim-scripts/c.vim.git bundle/c
  git submodule add https://github.com/vim-scripts/fortran.vim.git bundle/fortran
  git submodule add https://github.com/vim-scripts/bash-support.vim.git bundle/bash
  git submodule add https://github.com/vim-scripts/perl-support.vim.git bundle/perl-support
  git submodule add https://github.com/vim-scripts/CRefVim.git bundle/CRef
  git submodule add https://github.com/vim-scripts/stlrefvim.git bundle/stlrefvim
  git submodule add https://github.com/vim-scripts/tex.vim.git bundle/tex
  git submodule add https://github.com/vim-scripts/taglist.vim.git bundle/taglist
  git submodule add https://github.com/vim-scripts/snippets.vim.git bundle/snippets
  git submodule add https://github.com/wincent/Command-T.git bundle/command-t
  